### PR TITLE
feat: expose params to optimize base64 images

### LINKED ISSUE #171: Configurable parameters for `getPlaiceholder`
I use this library for progressive image rendering in next.js.
I noticed that when the image is upgraded from the placeholder a blinking effect occurs.
Looking at both the images i could clearly see that the placeholder image was brighter than the original image.
This effect is exaggerated with lower amounts of blur filter.
Digging through the source code, i stumbled upon this section.

packages/plaiceholder/src/get-image.ts:157
```js
const getOptimizedForBase64 = pipeline
    .clone()
    .normalise()
    .modulate({ saturation: 1.2, brightness: 1 })
    .removeAlpha()
    .toBuffer({ resolveWithObject: true });
```

Could we perhaps include a `saturation` param for `getPlaiceholder` to allow end users to configure this for their needs?

example
```js
const { base64, img } = await getPlaiceholder(
      'image.jpg',
      { size: 10, saturation: 1 }
);
```

### PR DESCRIPTION
**Pull request by joeyhage**
### Description

Alternative way to solve #171 with documentation.

### Additional context

Closes #171

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [X] New Feature
- [X] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Read the [Contributing Guidelines](https://github.com/joe-bell/plaiceholder/blob/main/CONTRIBUTING.md).
- [X] Follow the [Style Guide](https://github.com/joe-bell/plaiceholder/blob/main/CONTRIBUTING.md#style-guide).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by joe-bell** [comment]
Thanks for the alternative approach! I'm cautious of adding this in just yet – need some time to properly review the proposal and test

**Comment by joelpierre** [comment]
@joe-bell. Was there any progress on this? This feels like a sensible approach to it and exposing these config options is a great addition. The only issue is if there are other chainable methods that need exposing?

**Comment by joe-bell** [comment]
No progress as of yet. It's on my todo list, but I'm prioritising other things in life at the moment

**Comment by joe-bell** [comment]
Thanks for your efforts on this @joeyhage, I'll be implementing via #214

With your permission, I'd love to include you as a co-author to the relevant commits. Let me know over in #214, and once it's ready I'll include you 🙏

**Pull request closed without merging**
