### PR TITLE
Allow Custom Dir

### LINKED ISSUE #165: Base folder for options (for nx with nextjs)
**Is your feature request related to a problem? Please describe.**
I'm using `nx` with `nextjs` and my folder structure is different than the original. It's a monorepo, and the `public` folder in nested inside many levels. Example:
```
happynrwl/
├── apps
│   ├── tuskdesk
│   │   ├── index.d.ts
│   │   ├── jest.config.js
│   │   ├── next-env.d.ts
│   │   ├── next.config.js
│   │   ├── pages
│   │   │   ├── _app.tsx
│   │   │   ├── index.module.css
│   │   │   ├── index.tsx
│   │   │   └── styles.css
│   │   ├── public <--- public is not inside the root folder
```

Please see: https://nx.dev/l/r/guides/nextjs

**Describe the solution you'd like**
I'd like to have an optional `baseFolder` prop (name can be different of course) for the IGetPlaiceholderOptions, where I can override the hard coded `./public` for images 
https://github.com/joe-bell/plaiceholder/blob/67ed723f8ea0b8ad43d627477040b1db135d54cb/packages/plaiceholder/src/get-image.ts#L105

**Describe alternatives you've considered**
Currently the workaround is to have two `public` folders: one in my root and one inside the `nextjs` project's root.

**Additional context**
Thank you for this wonderful plugin, I really appreciate your work!

### PR DESCRIPTION
**Pull request by joe-bell**
### Description

Fixes #165, alternative solution to #198

### Additional context

N/A

---

### What is the purpose of this pull request?

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/joe-bell/plaiceholder/blob/main/CONTRIBUTING.md).
- [ ] Follow the [Style Guide](https://github.com/joe-bell/plaiceholder/blob/main/CONTRIBUTING.md#style-guide).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by joe-bell** [comment]
@JaeSeoKim rather than going back and forth to resolve trivial formatting changes, I went ahead and made the change. I really appreciate your efforts in contributing, so if it isn't too weird, can I mark you as a co-contributor on these commits? 

(with your permission of course)

**Comment by JaeSeoKim** [comment]
@joe-bell Of course it's good! Thank you for maintaining and developing a good open source! 😄

**Comment by joe-bell** [comment]
@JaeSeoKim consider it done, thank you!

Please do you mind giving `plaiceholder@2.5.0-beta.0` a test and letting me know if it works for your use case? It's working for me, but I'd love to know how you get on

**Comment by JaeSeoKim** [comment]
@joe-bell It works well as I want!
Import of blur-base64 data from `plaiceholder@2.5.0-beta.0` of remark plugin was successful.

**Comment by joe-bell** [comment]
@JaeSeoKim woohoo let’s do it!

**Pull request merged**
